spring:
  datasource:
    druid:
      #JDBC \u914D\u7F6E
      username: athnabyw
      password: 19970821
      url: jdbc:mysql://localhost:3306/managersystem?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver


      #\u8FDE\u63A5\u6C60\u914D\u7F6E(\u53EF\u9009)
      # \u8FDE\u63A5\u6C60\u7684\u914D\u7F6E\u4FE1\u606F\u521D\u59CB\u5316\u5927\u5C0F\uFF0C\u6700\u5C0F\uFF0C\u6700\u5927
      name: testDruidDataSource
      initial-size: 5    #\u521D\u59CB\u5316\u8FDE\u63A5\u5927\u5C0F
      max-active: 20    #\u6700\u5927\u8FDE\u63A5\u6570
      min-idle: 5        #\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5\u6570
      max-wait: 60000   # \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4


      #######\u76D1\u63A7\u914D\u7F6E  \u8BF4\u660E\u8BF7\u53C2\u8003Druid Wiki
      #\u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762sql\u65E0\u6CD5\u7EDF\u8BA1\uFF0C'wall'\u7528\u4E8E\u9632\u706B\u5899
      filters: stat,wall

      #\u914D\u7F6E Web Stat Filter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
        principal-session-name: session_name
        principal-cookie-name: cookie_name
        profile-enable:

      # Stat View Servlet \u914D\u7F6E  \u914D\u7F6E\u9ED8\u8BA4false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false   #\u7981\u7528HTML\u9875\u9762\u4E0A\u7684\u201CReset All\u201D\u529F\u80FD
        login-username: root  #\u76D1\u63A7\u9875\u9762\u767B\u5F55\u7684\u7528\u6237\u540D
        login-password: 19970821  #\u76D1\u63A7\u9875\u9762\u767B\u5F55\u7684\u5BC6\u7801
        #IP\u767D\u540D\u5355(\u6CA1\u6709\u914D\u7F6E\u6216\u8005\u4E3A\u7A7A\uFF0C\u5219\u5141\u8BB8\u6240\u6709\u8BBF\u95EE)
        allow:
        #IP\u9ED1\u540D\u5355 (\u5B58\u5728\u5171\u540C\u65F6\uFF0Cdeny\u4F18\u5148\u4E8Eallow)
        deny:

      # Spring\u76D1\u63A7\u914D\u7F6E\uFF0C\u8BF4\u660E\u8BF7\u53C2\u8003Druid Github Wiki\uFF0C\u914D\u7F6E_Druid\u548CSpring\u5173\u8054\u76D1\u63A7\u914D\u7F6E
      aop-patterns: com.byw.service.*


#=================================#
  thymeleaf:
    cache: false  #\u5173\u95ED\u6A21\u677F\u5F15\u64CE\u7F13\u5B58

  messages:
    basename: i18n.login  #\u56FD\u9645\u5316

  mvc:
    format:
      date: yyyy-MM-dd  #\u914D\u7F6E\u65E5\u671F\u683C\u5F0F

server:
  servlet:
    context-path: /MS  #\u914D\u7F6E\u9879\u76EE\u540D \u4EE5\u524Dtomcat\u7684\u865A\u62DF\u8DEF\u5F84
  port: 9000


#=================mybatis=================#
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml  #\u914D\u7F6Emapper\u4F4D\u7F6E
  type-aliases-package: com.byw.pojo  #\u914D\u7F6E\u522B\u540D \u5305\u626B\u63CF
