logging:
  config:
    classpath: logback-spring.xml


spring:
  datasource:
    druid:
      username: root
      #username: athnabyw
      password: 19970821
      #这里使用的docker0的id地址 172.18.0.1  等同于宿主机地址
      # 服务器地址 121.196.34.173
      # localhost
      url: jdbc:mysql://localhost:3306/managersystem?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver

      name: testDruidDataSource
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000

      filters: stat,wall

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
        principal-session-name: session_name
        principal-cookie-name: cookie_name
        profile-enable:


      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: root
        login-password: 19970821
        allow:

        deny:

      aop-patterns: com.byw.service.*


  #=================================#
  thymeleaf:
    cache: false

  messages:
    basename: i18n.login

  mvc:
    format:
      date: yyyy-MM-dd

server:
  servlet:
    context-path: /MS
  port: 9000


#=================mybatis=================#
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.byw.pojo



#定时任务
xxl:
  job:
    accessToken:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      address:
      appname: managersystem-study-xxl-job
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999
